# Generated by Django 5.1.15 on 2026-03-30 13:17

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2000)),
                ('page_type', models.CharField(choices=[('product', 'Product'), ('collection', 'Collection'), ('page', 'Page'), ('blog_post', 'Blog Post')], max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('h1', models.CharField(blank=True, default='', max_length=512)),
                ('content_score', models.IntegerField(default=0)),
                ('last_audited', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shopify_url', models.CharField(max_length=255, unique=True)),
                ('access_token', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('seo_score', models.IntegerField(default=0)),
                ('last_crawl_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(max_length=1000)),
                ('alt_text', models.TextField(blank=True, default='')),
                ('ai_generated_alt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('store', 'shopify_id')},
        ),
    ]
